services:
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - 'postgres:/var/lib/postgresql/data'
  redis:
    image: redis:6.2-alpine
    ports:
      - "6379:6379"
    volumes:
      - 'redis:/data'
  web:
    depends_on:
      - 'postgres'
      - 'redis'
    build:
      context: .
      dockerfile: Dockerfile.production
    image: ${DOCKER_WEB_IMAGE}
    command: bash -c "bundle exec rails s -b 0.0.0.0 -p 4000"
    ports:
      - '${DOCKER_HOST_WEB_PORT:-4000}:4000'
    volumes:
      - 'bundle_cache:/bundle'
      - '.:/app'
      - .env:/app/.env
    environment:
      REDIS_URL: redis://redis:6379/0
      DB_HOST: postgres
      DB_PORT: 5432
      DISABLE_SPRING: 1

volumes:
  redis:
  postgres:
  bundle_cache:
